apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: ms
spec:
  selector:
    service: microservico
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
