apiVersion: v1
kind: Service
metadata:
  name: jogo-adivinhacao-backend-service
  namespace: ms  
spec:
  selector:
    app: microservico  
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 5000  
  type: ClusterIP       
