apiVersion: v1
kind: Service
metadata:
  name: jogo-adivinhacao-frontend-service
  namespace: ms
spec:
  selector:
    service: microservico
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 80  
      nodePort: 30080  
  type: NodePort 
