apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ms
spec:
  selector:
    service: microservico
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 80  
  type: ClusterIP  
