apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend-service
  namespace: ms
spec:
  selector:
    app: nginx-frontend
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80  
  type: LoadBalancer  
